import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className + " min-h-screen flex flex-col bg-[#0e0e0e]"}
      >
        {/* <div className="min-h-screen flex flex-col bg-[#0e0e0e]">

        </div> */}
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
