import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: childrenProps) {
  return (
    <html lang={locale}>
      <UserProvider>
        <body
          className={`${inter.className} text-[#0e0e0e] dark:text-white  bg-[#f6f6f6] dark:bg-[#0e0e0e]  min-h-screen flex flex-col justify-between `}
        >
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
