import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body
        className={`${inter.className} text-[#0e0e0e] dark:text-white  bg-[#f6f6f6] dark:bg-[#0e0e0e]  min-h-screen flex flex-col justify-between `}
      >
        {children}
      </body>
    </html>
  );
}
